jobs:
  affectedApps:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.build.outputs.AFFECTED_APPS }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          echo "AFFECTED_APPS=$(npx nx show projects --affected --base=origin/$GITHUB_BASE_REF)" >> $GITHUB_OUTPUT