module.exports = {
  compileOnSave: false,
  compilerOptions: {
    rootDir: '.',
    noUnusedLocals: true,
    sourceMap: true,
    declaration: false,
    moduleResolution: 'node',
    emitDecoratorMetadata: true,
    experimentalDecorators: true,
    importHelpers: true,
    allowSyntheticDefaultImports: true,
    esModuleInterop: true,
    /* Advanced Options */
    forceConsistentCasingInFileNames: true /* Disallow inconsistently-cased references to the same file. */,
    resolveJsonModule: true,
    target: 'ES2021',
    module: 'commonjs',
    outDir: './dist',
    typeRoots: ['node_modules/@types'],
    types: ['node', 'jest'],
    baseUrl: '.',
    paths: {
      'is-even': ['packages/is-even/src/index.ts'],
      'is-odd': ['packages/is-odd/src/index.ts'],
    },
  },
  exclude: ['node_modules', 'tmp'],
  coveragePathIgnorePatterns: ['testcases', 'index.ts', 'types.ts', 'setupTests.ts'],
  testResultsProcessor: 'jest-sonar-reporter',
  collectCoverage: true,
  collectCoverageFrom: ['**/*.{ts,js}', '!**/node_modules/**'],
  coverageDirectory: 'dist',
  coverageReporters: ['lcov'],
  testTimeout: 20000,
  workerIdleMemoryLimit: 0.2,
  coverageThreshold: {
    global: {
      functions: 90,
      lines: 90,
      statements: 90,
      branches: 90,
    },
  },
};
