on:
  workflow_call:
jobs:
  affectedApps:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affected.outputs.AFFECTED_APPS }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - id: affected
        run: |
          cd package-based
          echo $GITHUB_OUTPUT
          yarn install
          # AFFECTED_APPS=$(npx nx show projects --affected --base=origin/$GITHUB_BASE_REF)
          AFFECTED_APPS="a b"
          echo "AFFECTED_APPS=$AFFECTED_APPS" >> $GITHUB_OUTPUT