name: CI
on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - main

jobs:
  callAffectedApps:
    uses: actions/checkout@v3
    uses: ./.github/workflows/affected.yml
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affectedApps.outputs.AFFECTED_APPS }}
  
  is_even_buid:
    runs-on: ubuntu-latest
    needs: callAffectedApps
    if: contains(needs.callAffectedApps.outputs.affected, 'is-event')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - run: |
          ls
  
  is_odd_buid:
    runs-on: ubuntu-latest
    needs: callAffectedApps
    if: contains(needs.callAffectedApps.outputs.affected, 'is-odd')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          ls
