name: CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
         env
         yarn --version
         node --version
         echo $NX_BASE
         echo $NX_HEAD
         ls
         cd package-based
         yarn install
         ls
         npx nx run-many -t build

      - uses: SamhammerAG/last-successful-build-action@v4
        with:
          branch: main
          workflow: "build"

