name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn --version
      - run: node --version
      - run: yarn install
      - run: ls
      - run: cd package-based
      - run: ls
      - run: npx nx affected -t build --base=main
