name: title check

on:
  pull_request:
    branches: main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^(fix|feat|chore|ci|refactor|breaking|revert|perf|docs)\\(.+\\).+"